version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile-model
      context: .
    image: app/model
    restart: always
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ../app:/app



  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../db:/docker-entrypoint-initdb.d/:ro

